# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k410tiffg900-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/newpprsdn/linkden_proj/tfp1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/newpprsdn/linkden_proj/tfp1/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/newpprsdn/linkden_proj/tfp1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library ieee_proposed {
  D:/newpprsdn/linkden_proj/tfp1/project_1/project_1.srcs/sources_1/imports/ieee_proposed/fixed_float_types_c.vhdl
  D:/newpprsdn/linkden_proj/tfp1/project_1/project_1.srcs/sources_1/imports/ieee_proposed/fixed_pkg_c.vhdl
  D:/newpprsdn/linkden_proj/tfp1/project_1/project_1.srcs/sources_1/imports/ieee_proposed/float_pkg_c.vhdl
}
read_vhdl -library xil_defaultlib D:/newpprsdn/linkden_proj/tfp1/project_1/project_1.srcs/sources_1/imports/tfp1/fpadd_1.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top fpadd_1 -part xc7k410tiffg900-2L


write_checkpoint -force -noxdef fpadd_1.dcp

catch { report_utilization -file fpadd_1_utilization_synth.rpt -pb fpadd_1_utilization_synth.pb }
